### PR TITLE
Bump the dependency on 'snap-core'.

### PR DESCRIPTION
**Pull request by 23Skidoo**
Allows using `snap-blaze` with the Git version of Snap.

### CODE REVIEW

**Comment by 23Skidoo** [comment]
@jaspervdj Ping.

**Comment by jaspervdj** [comment]
I don't *really* mind merging this in, but are we sure it is going to work with the upcoming version? It is still possible for the API to change in the git version, no?

**Comment by 23Skidoo** [comment]
Snap 1.0 is basically done, the only thing they want to change API-wise is some command-line processing code. It's highly unlikely that those changes will break `snap-blaze`.

**Comment by wereHamster** [comment]
This change has already been applied in #7. Can be closed.

**Comment by 23Skidoo** [comment]
@wereHamster Thanks for the heads-up!

**Pull request closed without merging**
